services:
  mysql:
    image: mysql:8.0
    container_name: threads-mysql
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: threads_db
      MYSQL_USER: threads_user
      MYSQL_PASSWORD: threadspassword
    ports:
      - "3306:3306"
    volumes:
      - ./docker/mysql-data:/var/lib/mysql

  nginx:
    image: nginx:alpine
    container_name: threads-nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./nginx/certs:/etc/nginx/conf.d/cert.pem
      - ./nginx/certs:/etc/nginx/conf.d/key.pem
    restart: unless-stopped
    networks:
      - threads-network

  redis:
    image: redis:8.6.2-alpine
    container_name: threads-redis
    ports:
      - "127.0.0.1:6379:6379"
    volumes:
      - ./docker/redis-data:/data
    restart: unless-stopped
    networks:
      - threads-network

  redis-insight:
    image: redislabs/redisinsight:3.4
    container_name: threads-redis-insight
    ports:
      - "5540:5540"
    restart: unless-stopped
    networks:
      - threads-network

volumes:
  redis-data:
  mysql-data:

networks:
  threads-network:
