version: "3.8"

services:
  api:
    image: ${IMAGE_URL}
    container_name: threads-api
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "3302:3302"
    depends_on:
      - redis
    networks:
      - threads-network

  worker:
    image: ${IMAGE_URL}
    container_name: threads-worker
    restart: unless-stopped
    command: npm run worker
    env_file:
      - .env
    depends_on:
      - redis
    networks:
      - threads-network

  redis:
    image: redis:alpine # Khuyên dùng bản alpine thường cho nhẹ và ổn định
    container_name: threads-redis
    restart: unless-stopped
    networks:
      - threads-network

  nginx:
    image: nginx:alpine
    container_name: threads-nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
    restart: unless-stopped
    depends_on:
      - api
    networks:
      - threads-network

networks:
  threads-network:
    driver: bridge
