services:
  redis:
    image: redis:8.6.2-alpine
    container_name: threads-redis
    ports:
      - "127.0.0.1:6379:6379"
    volumes:
      - ./docker/redis-data:/data
    restart: unless-stopped
    networks:
      - threads-network

  redis-insight:
    image: redislabs/redisinsight:3.4
    container_name: threads-redis-insight
    ports:
      - "5540:5540"
    restart: unless-stopped
    networks:
      - threads-network

volumes:
  redis-data:

networks:
  threads-network:
