services:
  api:
    image: ${IMAGE_URL}
    container_name: threads-api
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "3302:3302"
    depends_on:
      - redis
    networks:
      - threads-network

  worker:
    image: ${IMAGE_URL}
    container_name: threads-worker
    restart: unless-stopped
    command: npm run start:worker
    env_file:
      - .env
    depends_on:
      - redis
    networks:
      - threads-network

  redis:
    image: redis:alpine # Khuyên dùng bản alpine thường cho nhẹ và ổn định
    container_name: threads-redis
    restart: unless-stopped
    networks:
      - threads-network

  soketi:
    image: quay.io/soketi/soketi:1.6.1-16-alpine
    container_name: threads-soketi
    restart: unless-stopped
    env_file:
      - .env
    environment:
      SOKETI_DEFAULT_APP_ID: ${PUSHER_APP_ID}
      SOKETI_DEFAULT_APP_KEY: ${PUSHER_KEY}
      SOKETI_DEFAULT_APP_SECRET: ${PUSHER_SECRET}
      SOKETI_DEFAULT_APP_ENABLE_CLIENT_MESSAGES: "true"
    ports:
      - "6001:6001"
    networks:
      - threads-network

  nginx:
    image: nginx:alpine
    container_name: threads-nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d:ro
    restart: unless-stopped
    depends_on:
      - api
    networks:
      - threads-network

networks:
  threads-network:
    driver: bridge
