import { swaggerDocument } from '@/config/swagger';
import { authorization } from '@/middlewares/auth';
import { adminHandler } from '@/middlewares/admin';
import adminRouter from '@/modules/admin/admin.routes';
import authRouter from '@/modules/auth/auth.routes';
import circleRouter from '@/modules/circle/circle.routes';
import healthRouter from '@/modules/health/health.routes';
import knowledgePostCommentRouter from '@/modules/knowledge-post-comment/knowledge-post-comment.route';
import knowledgePostRouter from '@/modules/knowledge-post/knowledge-post.route';
import knowledgeRankingRouter from '@/modules/knowledge-ranking/knowledge-ranking.route';
import notificationRouter from '@/modules/notification/notification.route';
import postRouter from '@/modules/post/post.routes';
import topicRouter from '@/modules/topic/topic.route';
import uploadRouter from '@/modules/upload/upload.routes';
import userFollowRouter from '@/modules/user/user-follow.routes';
import userRouter from '@/modules/user/user.routes';
import usersRouter from '@/modules/user/users.routes';
import webhooksRouter from '@/modules/webhooks/router';
import { Router } from 'express';
import swaggerUi from 'swagger-ui-express';

const router = Router();
router.use('/docs', swaggerUi.serve, swaggerUi.setup(swaggerDocument));
router.use('/admin', authorization, adminHandler, adminRouter);
router.use('/auth', authRouter);
router.use('/circle', circleRouter);
router.use('/health', healthRouter);
router.use('/me', userRouter);
router.use('/users', usersRouter);
router.use('/user', userFollowRouter);
router.use('/upload', uploadRouter);
router.use('/posts', postRouter);
router.use('/topic', topicRouter);
router.use('/knowledge-posts', knowledgePostRouter);
router.use('/knowledge-post-comments', knowledgePostCommentRouter);
router.use('/knowledge-rankings', knowledgeRankingRouter);
router.use('/notification', notificationRouter);
router.use('/webhooks', webhooksRouter);

export default router;
