-- AlterTable
ALTER TABLE `anti_spam` MODIFY `action` ENUM('POST_CREATED', 'POST_DELETED', 'LIKE_CREATED', 'FLOW_FOLLOWER_CREATED', 'FOLLOW_FOLLOWING_CREATED', 'QUOTE_CREATED', 'QUOTE_DELETED', 'SHARE_CREATED', 'SHARE_DELETED', 'INVITE_SENT', 'INVITE_ACCEPTED', 'JOIN_CIRCLE', 'LEAVE_CIRCLE', 'GENERATE_POST_BEAUTIFUL') NOT NULL;

-- AlterTable
ALTER TABLE `daily_quests` MODIFY `action_enum` ENUM('POST_CREATED', 'POST_DELETED', 'LIKE_CREATED', 'FLOW_FOLLOWER_CREATED', 'FOLLOW_FOLLOWING_CREATED', 'QUOTE_CREATED', 'QUOTE_DELETED', 'SHARE_CREATED', 'SHARE_DELETED', 'INVITE_SENT', 'INVITE_ACCEPTED', 'JOIN_CIRCLE', 'LEAVE_CIRCLE', 'GENERATE_POST_BEAUTIFUL') NOT NULL;

-- AlterTable
ALTER TABLE `user_action_logs` MODIFY `type_enum` ENUM('POST_CREATED', 'POST_DELETED', 'LIKE_CREATED', 'FLOW_FOLLOWER_CREATED', 'FOLLOW_FOLLOWING_CREATED', 'QUOTE_CREATED', 'QUOTE_DELETED', 'SHARE_CREATED', 'SHARE_DELETED', 'INVITE_SENT', 'INVITE_ACCEPTED', 'JOIN_CIRCLE', 'LEAVE_CIRCLE', 'GENERATE_POST_BEAUTIFUL') NOT NULL;

-- CreateTable
CREATE TABLE `webhook_preview_images` (
    `id` INTEGER NOT NULL AUTO_INCREMENT,
    `user_id` VARCHAR(191) NOT NULL,
    `draft_id` VARCHAR(191) NOT NULL,
    `generation_id` VARCHAR(191) NOT NULL,
    `content` VARCHAR(2048) NOT NULL,
    `metadata` JSON NULL,
    `created_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `updated_at` DATETIME(3) NOT NULL,

    UNIQUE INDEX `webhook_preview_images_generation_id_key`(`generation_id`),
    INDEX `idx_webhook_preview_images_draft_id`(`draft_id`),
    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- AddForeignKey
ALTER TABLE `webhook_preview_images` ADD CONSTRAINT `webhook_preview_images_user_id_fkey` FOREIGN KEY (`user_id`) REFERENCES `users`(`id`) ON DELETE RESTRICT ON UPDATE CASCADE;
