-- AlterTable
ALTER TABLE `anti_spam` MODIFY `action` ENUM('POST_CREATED', 'POST_DELETED', 'LIKE_CREATED', 'FLOW_FOLLOWER_CREATED', 'FOLLOW_FOLLOWING_CREATED', 'QUOTE_CREATED', 'QUOTE_DELETED', 'SHARE_CREATED', 'SHARE_DELETED', 'INVITE_SENT', 'INVITE_ACCEPTED', 'JOIN_CIRCLE', 'LEAVE_CIRCLE', 'GENERATE_POST_BEAUTIFUL', 'GENERATE_CAPTION_MD', 'GENERATE_IMAGE') NOT NULL;

-- AlterTable
ALTER TABLE `daily_quests` MODIFY `action_enum` ENUM('POST_CREATED', 'POST_DELETED', 'LIKE_CREATED', 'FLOW_FOLLOWER_CREATED', 'FOLLOW_FOLLOWING_CREATED', 'QUOTE_CREATED', 'QUOTE_DELETED', 'SHARE_CREATED', 'SHARE_DELETED', 'INVITE_SENT', 'INVITE_ACCEPTED', 'JOIN_CIRCLE', 'LEAVE_CIRCLE', 'GENERATE_POST_BEAUTIFUL', 'GENERATE_CAPTION_MD', 'GENERATE_IMAGE') NOT NULL;

-- AlterTable
ALTER TABLE `user_action_logs` MODIFY `type_enum` ENUM('POST_CREATED', 'POST_DELETED', 'LIKE_CREATED', 'FLOW_FOLLOWER_CREATED', 'FOLLOW_FOLLOWING_CREATED', 'QUOTE_CREATED', 'QUOTE_DELETED', 'SHARE_CREATED', 'SHARE_DELETED', 'INVITE_SENT', 'INVITE_ACCEPTED', 'JOIN_CIRCLE', 'LEAVE_CIRCLE', 'GENERATE_POST_BEAUTIFUL', 'GENERATE_CAPTION_MD', 'GENERATE_IMAGE') NOT NULL;

-- AlterTable
ALTER TABLE `user_restrictions` MODIFY `type_enum` ENUM('POSTING', 'POST_AND_USE_KARMA', 'AI_GENERATION_CAPTION', 'AI_GENERATION_IMAGE') NOT NULL;

-- CreateTable
CREATE TABLE `limit_actions` (
    `id` INTEGER NOT NULL AUTO_INCREMENT,
    `user_id` VARCHAR(191) NOT NULL,
    `type_enum` ENUM('POST_CREATED', 'POST_DELETED', 'LIKE_CREATED', 'FLOW_FOLLOWER_CREATED', 'FOLLOW_FOLLOWING_CREATED', 'QUOTE_CREATED', 'QUOTE_DELETED', 'SHARE_CREATED', 'SHARE_DELETED', 'INVITE_SENT', 'INVITE_ACCEPTED', 'JOIN_CIRCLE', 'LEAVE_CIRCLE', 'GENERATE_POST_BEAUTIFUL', 'GENERATE_CAPTION_MD', 'GENERATE_IMAGE') NOT NULL,
    `count` INTEGER NOT NULL DEFAULT 5,
    `reset_at` DATETIME(3) NOT NULL,

    INDEX `idx_limit_actions_user_id`(`user_id`),
    INDEX `idx_limit_actions_type`(`type_enum`),
    INDEX `idx_limit_actions_reset_at`(`reset_at`),
    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- AddForeignKey
ALTER TABLE `limit_actions` ADD CONSTRAINT `limit_actions_user_id_fkey` FOREIGN KEY (`user_id`) REFERENCES `users`(`id`) ON DELETE RESTRICT ON UPDATE CASCADE;
