name: Build

on:
  workflow_dispatch:
  push:
    branches:
      - production
      - dev

concurrency:
  group: production-deploy
  cancel-in-progress: false

permissions:
  contents: read
  packages: write
  id-token: write

jobs:
  build:
    environment: production
    runs-on: ubuntu-latest

    outputs:
      image: ${{ steps.set-image.outputs.uri }}

    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js 20.x
        uses: actions/setup-node@v3
        with:
          node-version: 20.x
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.ROLE_GITHUB_ACTION }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build, tag, and push image to Amazon ECR
        env:
          REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          REPOSITORY: ${{ secrets.ECR_REPOSITORY }}
          IMAGE_TAG: ${{ github.sha }}
        run: |
          docker build \
            -t $REGISTRY/$REPOSITORY:$IMAGE_TAG \ 
            -t $REGISTRY/$REPOSITORY:production \
            .

          docker push $REGISTRY/$REPOSITORY:$IMAGE_TAG
          docker push $REGISTRY/$REPOSITORY:production

  deploy:
    needs: build
    runs-on: self-hosted
    environment: production
    if: github.ref == 'refs/heads/production'

    steps:
      - name: Login to GHCR
        run: |
          echo ${{ github.token }} | docker login ghcr.io \
            -u ${{ github.actor }} --password-stdin

      - name: Create .env
        run: |
          echo "${{ secrets.ENV_FILE }}" > /home/ubuntu/.env

      - name: Pull image
        run: docker pull ${{ needs.build.outputs.image }}
